# Generated by Django 2.1.9 on 2019-06-22 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='prime',
            new_name='price',
        ),
    ]
